name: Run Autoclaim

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */15 * * *'

concurrency:
  group: 'pythonC'  # 设置唯一的组ID
  cancel-in-progress: true 

jobs:
  Blum:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: 'true'
    timeout-minutes: 900  # 设置超时时间为15小时
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15  # 选择 Python 版本

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/1
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Run Blum
        run: |
          cd app/1
          wget ${{ env.SESSION_CONFIG }}/1/data.txt
          wget ${{ env.SESSION_CONFIG }}/1/database.sqlite3
          chmod +x data.txt database.sqlite3
          ./venv/bin/python3 bot.py -A 6  # 运行第一个Python脚本

  MemeFi:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 900  # 设置超时时间为15小时
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/2
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/2
          wget ${{ env.SESSION_CONFIG }}/2/.env
          chmod +x .env
          mkdir sessions
          cd sessions
          wget ${{ env.SESSION_CONFIG }}/sessions/Suyunjing-1.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Sumengjing-2.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Susus-3.session
          chmod +x Suyunjing-1.session Sumengjing-2.session Susus-3.session

      - name: Run Python MemeFi
        run: |
          cd app/2
          ./venv/bin/python3 main.py -a 2  # 运行第二个Python脚本

  TimeFarm:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 900  # 设置超时时间为15小时
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/3
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/3
          wget ${{ env.SESSION_CONFIG }}/3/.env
          chmod +x .env
          mkdir sessions
          cd sessions
          wget ${{ env.SESSION_CONFIG }}/sessions/Suyunjing-1.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Sumengjing-2.session
          chmod +x Suyunjing-1.session Sumengjing-2.session

      - name: Run Python TimeFarm
        run: |
          cd app/3
          ./venv/bin/python3 main.py -a 2  # 运行第三个Python脚本

  Tomarket:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 900  # 设置超时时间为15小时
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/4
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/4
          wget ${{ env.SESSION_CONFIG }}/4/.env
          chmod +x .env
          mkdir sessions
          cd sessions
          wget ${{ env.SESSION_CONFIG }}/sessions/Suyunjing-1.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Sumengjing-2.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Susus-3.session
          chmod +x Suyunjing-1.session Sumengjing-2.session Susus-3.session

      - name: Run Python Tomarket
        run: |
          cd app/4
          ./venv/bin/python3 main.py -a 1  # 运行第三个Python脚本

  YesCoin:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 900  # 设置超时时间为15小时
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/5
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/5
          wget ${{ env.SESSION_CONFIG }}/5/.env
          chmod +x .env
          mkdir sessions
          cd sessions
          wget ${{ env.SESSION_CONFIG }}/sessions/Suyunjing-1.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Sumengjing-2.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Susus-3.session
          chmod +x Suyunjing-1.session Sumengjing-2.session Susus-3.session

      - name: Run Python YesCoin
        run: |
          cd app/5
          ./venv/bin/python3 main.py -a 2  # 运行第三个Python脚本

  Duckchain:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: 'false'
    timeout-minutes: 900  # 设置超时时间为15小时
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/6
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/6
          wget ${{ env.SESSION_CONFIG }}/6/data.txt
          chmod +x data.txt

      - name: Run Python Duckchain
        run: |
          cd app/6
          ./venv/bin/python3 main.py  # 运行第三个Python脚本

  Notpixel:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 900  # 设置超时时间为15小时
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/7
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/7
          wget ${{ env.SESSION_CONFIG }}/7/.env
          chmod +x .env
          mkdir sessions
          cd sessions
          wget ${{ env.SESSION_CONFIG }}/sessions/Suyunjing-1.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Sumengjing-2.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Susus-3.session
          wget ${{ env.SESSION_CONFIG }}/7/sessions/accounts.json
          chmod +x Suyunjing-1.session Sumengjing-2.session Susus-3.session

      - name: Run Python Notpixel
        run: |
          cd app/7
          ./venv/bin/python3 main.py -a 1  # 运行第三个Python脚本

  Major:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 900  # 设置超时时间为15小时
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/8
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/8
          wget ${{ env.SESSION_CONFIG }}/8/.env
          chmod +x .env
          mkdir sessions
          cd sessions
          wget ${{ env.SESSION_CONFIG }}/sessions/Suyunjing-1.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Sumengjing-2.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Susus-3.session
          chmod +x Suyunjing-1.session Sumengjing-2.session Susus-3.session

      - name: Run Python Major
        run: |
          cd app/8
          ./venv/bin/python3 main.py -a 1  # 运行第三个Python脚本

  Boinkers:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 900  # 设置超时时间为15小时
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/9
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/9
          wget ${{ env.SESSION_CONFIG }}/9/.env
          chmod +x .env
          mkdir sessions
          cd sessions
          wget ${{ env.SESSION_CONFIG }}/sessions/Suyunjing-1.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Sumengjing-2.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Susus-3.session
          chmod +x Suyunjing-1.session Sumengjing-2.session Susus-3.session

      - name: Run Python Boinkers
        run: |
          cd app/9
          ./venv/bin/python3 main.py -a 1  # 运行第三个Python脚本