name: Run Autoclaim

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

concurrency:
  group: 'pythonC'  # 设置唯一的组ID
  cancel-in-progress: true 

jobs:
  Delete:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 360  # 设置超时时间为15小时
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete old workflow runs
        uses: Suyunmeng/delete-old-workflow-runs@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 3600

  Blum:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 360  # 设置超时时间为15小时
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15  # 选择 Python 版本

      - name: Connect InnerWeb
        run: |
          cd app/warp
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/1
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Run Blum
        run: |
          cd app/1
          ./venv/bin/python3 bot.py -A 6  # 运行第一个Python脚本

  MemeFi:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 360  # 设置超时时间为15小时
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          cd app/warp
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/2
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Run Python MemeFi
        run: |
          cd app/2
          ./venv/bin/python3 main.py -a 2  # 运行第二个Python脚本

  TimeFarm:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 360  # 设置超时时间为15小时
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          cd app/warp
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/3
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Run Python TimeFarm
        run: |
          cd app/3
          ./venv/bin/python3 main.py -a 2  # 运行第三个Python脚本

  Tomarket:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 360  # 设置超时时间为15小时
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          cd app/warp
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/4
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Run Python Tomarket
        run: |
          cd app/4
          ./venv/bin/python3 main.py -a 1  # 运行第三个Python脚本

  YesCoin:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 360  # 设置超时时间为15小时
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          cd app/warp
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/5
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Run Python YesCoin
        run: |
          cd app/5
          ./venv/bin/python3 main.py -a 2  # 运行第三个Python脚本