name: Run Autoclaim

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

concurrency:
  group: 'pythonC'  # 设置唯一的组ID
  cancel-in-progress: true 

jobs:
  Blum:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 225
    if: 'true'
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/1
          npm install

      - name: Run Blum
        run: |
          cd app/1/src/data
          wget ${{ env.SESSION_CONFIG }}/1/users.txt
          chmod +x users.txt
          npm run start  # 运行第一个Python脚本

  MemeFi:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: false
    timeout-minutes: 225
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/2
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/2
          wget ${{ env.SESSION_CONFIG }}/2/.env
          chmod +x .env
          mkdir sessions
          cd sessions
          wget ${{ env.SESSION_CONFIG }}/sessions/Suyunjing-1.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Sumengjing-2.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Susu-3.session
          chmod +x Suyunjing-1.session Sumengjing-2.session Susu-3.session

      - name: Run Python MemeFi
        run: |
          cd app/2
          ./venv/bin/python3 main.py -a 2  # 运行第二个Python脚本

  TimeFarm:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: false
    timeout-minutes: 225
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/3
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/3
          wget ${{ env.SESSION_CONFIG }}/3/.env
          chmod +x .env
          mkdir sessions
          cd sessions
          wget ${{ env.SESSION_CONFIG }}/sessions/Suyunjing-1.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Sumengjing-2.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Susu-3.session
          chmod +x Suyunjing-1.session Sumengjing-2.session Susu-3.session

      - name: Run Python TimeFarm
        run: |
          cd app/3
          ./venv/bin/python3 main.py -a 2  # 运行第三个Python脚本

  Tomarket:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 225
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/4
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/4
          wget ${{ env.SESSION_CONFIG }}/4/.env
          chmod +x .env
          mkdir sessions
          cd sessions
          wget ${{ env.SESSION_CONFIG }}/sessions/Suyunjing-1.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Sumengjing-2.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Susu-3.session
          chmod +x Suyunjing-1.session Sumengjing-2.session Susu-3.session

      - name: Run Python Tomarket
        run: |
          cd app/4
          ./venv/bin/python3 main.py -a 1  # 运行第三个Python脚本

  YesCoin:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 225
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/5
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/5
          wget ${{ env.SESSION_CONFIG }}/5/.env
          chmod +x .env
          mkdir sessions
          cd sessions
          wget ${{ env.SESSION_CONFIG }}/sessions/Suyunjing-1.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Sumengjing-2.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Susu-3.session
          chmod +x Suyunjing-1.session Sumengjing-2.session Susu-3.session

      - name: Run Python YesCoin
        run: |
          cd app/5
          ./venv/bin/python3 main.py -a 2  # 运行第三个Python脚本
